name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Install Playwright browsers
    - name: Install Playwright browsers
      run: npx playwright install

    # Step 5: Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        docker compose -f ./docker/docker-compose.yml up -d
        docker ps

    # Step 6: Test if http://localhost:8002/ is available
    - name: Test if service is up
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8002/; then
            echo "Service is up!";
            exit 0;
          else
            echo "Waiting for service to be available...";
            sleep 5;
          fi;
        done;
        echo "Service did not start in time!";
        exit 1;

    # Step 7: Run tests
    - name: Run tests
      run: npm run test

    # Step 8: Shutdown Docker Compose
    - name: Shutdown Docker Compose
      if: always()
      run: docker compose -f ./docker/docker-compose.yml down

    # Step 9: Upload Mochawesome report
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report
        path: mochawesome-report/